Fix compiler warning/error about typedef redefinitions
Per buildfarm member 'sifaka':

    procsignal.c:87:3: error: redefinition of typedef 'ProcSignalHeader' is a C11 feature [-Werror,-Wtypedef-redefinition]

(cherry picked from commit 8bda213ec1628737b500b6b04ec164aec354eb04)